### ISSUE TITLE
Как настроить оповещения на телефон или почту?

### ISSUE THREAD

**Issue by dganic** [mdevaev/emonoda#38]
Судя из описания в emonoda появилась мега фича
"Оповещения -- можно добавить emfetch в крон и забыть о нем, при появлении новых раздач программа вышлет оповещение вам на почту или телефон"

Срочно расскажите как это настроить, нет времени ждать! :)
Заранее спасибо!

**Comment by mdevaev** [comment]
Что именно, телефон или почту?

**Comment by dganic** [comment]
Интересует оба варианта, телефон через какие-то сторонние платные сервисы? 
На почту я так понимаю за бесплатно?

**Comment by mdevaev** [comment]
Телефон через http://notifymyandroid.com/. Регистрируетесь там, ставите приложение и получаете ключик, который прописываете в конфиг:
```yaml
confetti:
    nma:
        api_keys: 1234567890
```
С почтой нужно так (если у вас акк на яндекс-почте):
```yaml
confetti:
    email:
        to: mdevaev@gmail.com // получатель
        server: smtp.yandex.ru
        ssl: true
        user: ya.silverna  // аккаунт отпровителя на яндексе
        passwd: secret
        sender: ya.silverna@yandex.ru // отправитель

**Comment by mdevaev** [comment]
Ну как, работает?

**Comment by dganic** [comment]
Письмо вроде отправилось, но принимающий сервер его не принял, сказал что это спам:

https://gist.github.com/dganic/947464daa8cebd6f9d71

**Comment by mdevaev** [comment]
Покажите конфигурацию.

**Comment by dganic** [comment]
core:
    torrents_dir: /var/lib/transmission/.config/transmission-daemon/torrents
    client: transmission

fetchers:
    rutracker.org:
        user: Dganic
        passwd: secret
    nnm-club.me:
        user: Dganic
        passwd: secret
    ipv6.nnm-club.me:
        user: Dganic
        passwd: secret
confetti:
    email:
        to: dganic@bmail.ru
        server: smtp.yandex.ru
        ssl: true
        user: dganic
        passwd: secret
        sender: dganic@yandex.ru

**Comment by mdevaev** [comment]
А если отправлять на gmail, например?

**Comment by dganic** [comment]
А несколько адресов можно написать? 
Теперь чтобы протестировать надо ждать пока какая-либо раздача обновится:( 
Или как-то можно вручную инициировать отправку почты?

**Comment by mdevaev** [comment]
Можно несколько, да:
```
confetti:
    email:
        to:
            - dganic@bmail.ru
            - ...
            - ...
        server: smtp.yandex.ru
        ssl: true
        user: dganic
        passwd: secret
        sender: dganic@yandex.ru
```
Вручную нельзя, если только добавить какой-нибудь старый торрент, а потом запустить обновление.
